[Feat] Game socket & API
Maserati-Quattroporte/maseraT_pong_game pull request #52
Opened 2022-07-12 13:53 UTC by yeslee-v

- create socket: `game-join-socket`, ``game-leave-socket`
- create API: gameRoomList, gameParticipantList
- **NOT YET position** in game.gateway

2022-07-13 03:01 UTC, hsw7703 requested changes
고쳐야 할 부분들 error 뜰 거 같은 부분들 comment 남겨 놨습니다. 확인후에 고쳐서 다시 pr 해주세요

2022-07-13 03:01 UTC, hsw7703 commented on backend/src/game/dto/game-participant.dto.ts
> +  userNickname: string;
userNickname 말고 그냥 nickname으로 하는게 더 좋지 않을까요? 다른데선 다 nickname으로 보내고 있어서..

2022-07-13 03:01 UTC, hsw7703 commented on backend/src/game/dto/game-room.dto.ts
> +  userNickname: string;
여기도 그냥 nickname으로

2022-07-13 03:01 UTC, hsw7703 commented on backend/src/game/game.gateway.ts
> +      if (gameParticipant.id === 1) {
gameParticipant에 아무 값도 없는데 id를 어떻게 비교하시죠? 선언만 해 놓으시고 아무 값도 안 집어 넣으셨는데

2022-07-13 03:01 UTC, hsw7703 commented on backend/src/game/game.gateway.ts
> +    if (!this.joinGameRoom(gameJoinDto, user)) return;
async 걸려있는 함수 await 없이 쓰시면 pending 넘어 올 거 같아서 이 부분에 await 걸어주셔야 할거 같아요. 한 번 확인해 주세요

2022-07-13 03:01 UTC, hsw7703 commented on backend/src/game/game.gateway.ts
> +    socket.join(gameParticipantDto.title);
저희 title 중복 되서 채팅방은 chat-id, 게임방은 game-id 이렇게 넣기로 했었는데 이 부분 수정해주세요.
socket.join("game-" + gameParticipantDto.gameRoomId) 이런 식으로

2022-07-13 03:01 UTC, hsw7703 commented on backend/src/game/game.gateway.ts
> +    socket.leave(gameLeaveDto.title);
join 하는 room이름 바꾸시면서 여기도 같이 바꿔주세요

2022-07-13 03:01 UTC, hsw7703 commented on backend/src/game/game.gateway.ts
> +      await this.gameParticipantRepository.findOne(gameLeaveDto.userId);
findOne에 where 안 넣어서 find하시면 participant pk로 find하는데 pk랑 userid랑은 다른 값이여서 원하는 값이 안 나오겠네요.
그리고 위에서 유저 delete하셔서 찾으시려고 하는 값도 없을 거 같구요

2022-07-13 03:01 UTC, hsw7703 commented on backend/src/game/game.service.ts
> +    private gameJoinRepository: GameRoomRepository,
이 부분은 이름 gameJoinRepository 보단 gameRoomRepository가 더 좋을 거 같아요

2022-07-13 03:01 UTC, hsw7703 commented on backend/src/game/game.service.ts
> +        relations: ["User"],
User -> user 로 바꾸셔야해요

2022-07-13 03:01 UTC, hsw7703 commented on backend/src/game/repository/game-room.repository.ts
> +    });
isStart, isLadder 둘 다 default 값 없어서 이렇게 하시면 error 뜰 거 같은데 확인해 보셨나요?

2022-07-13 04:17 UTC, yeslee-v commented on backend/src/game/dto/game-participant.dto.ts
> +  userNickname: string;
소켓 문서에 나와있는 그대로 입력했더니만..ㅋㅋ 접수하겠습니다

2022-07-13 04:29 UTC, yeslee-v commented on backend/src/game/game.gateway.ts
> +    socket.join(gameParticipantDto.title);
title이 중복된다는 것을 이해 못했어요

2022-07-13 04:31 UTC, yeslee-v commented on backend/src/game/game.gateway.ts
> +      if (gameParticipant.id === 1) {
번외로, id로 비교하는게 맞는지 몰라서 조건만 넣은거였는데 추가를 안했네요. 전에 말해주신 position 관련해서 이해를 잘 못했어서요.

2022-07-13 04:33 UTC, yeslee-v commented on backend/src/game/game.gateway.ts
> +    socket.join(gameParticipantDto.title);
방 제목을 애초에 입력받아서 title에 넣는게 아니었나요?

2022-07-13 06:57 UTC, jeongwle commented on backend/src/game/game.gateway.ts
> +    socket.join(gameParticipantDto.title);
방제목 자체가 중복 검사를 따로 하지 않기 떄문에 방1 이라는 title의 방을 아주 많이 생성할 수 있습니다. 그래서 구분하기 위해 room의 pk인 id를 넣어서 하자는 말인 것 같습니다.

2022-07-13 13:52 UTC, yeslee-v commented
position 저렇게 짜는거 맞는지요.. 흠...... 헷갈리네요.
그리고 request로 받는 title과 직접 넣어주는 초기의 title과는 다른 것 맞죠?

2022-07-14 05:07 UTC, hsw7703 requested changes
조금만 더 수정 하시면 될 거 같아요

2022-07-14 05:07 UTC, hsw7703 commented on backend/src/game/game.gateway.ts
> +    const gameRoom: GameRoom = await this.gameRoomRepository.findOne({
pk로 find 할 때는 where문 안 써도 되요~

2022-07-14 05:07 UTC, hsw7703 commented on backend/src/game/game.gateway.ts
> +    // 게임 첫 참여자는 무조건 leftUser인지?
넵!

2022-07-14 05:07 UTC, hsw7703 commented on backend/src/game/game.gateway.ts
> +      // participant id에 따라 position 결정
gameParticipants = this.gameParticipantRepository.find({
  where: {
    gameRoom: // 게임 룸 조회
  },
  order: {
    gamePosition: 1
  }
})
이렇게 조회하시면 position 오름차순 정렬로 나와서 [0], [1] user만 확인하시면 left, right중 어디 비어있는지 체크 가능할 거 같아요!

2022-07-14 05:07 UTC, hsw7703 commented on backend/src/game/game.gateway.ts
> +        id: gameLeaveDto.userId,
여기도 id로 조회할 땐 where 안 쓰셔도 되요

2022-07-14 14:31 UTC, yeslee-v commented on backend/src/game/game.gateway.ts
> +      // participant id에 따라 position 결정
흐어 gamePosition을 정해놓고 그걸 체크할 생각을 안했군요..ㅡㅡ

2022-07-14 14:43 UTC, yeslee-v commented on backend/src/game/game.gateway.ts
> +    const gameRoom: GameRoom = await this.gameRoomRepository.findOne({
ㅎ 이제 다 까먹는군요

2022-07-16 06:26 UTC, hsw7703 requested changes
다시!! 고쳐주세요

2022-07-16 06:26 UTC, hsw7703 commented on backend/src/game/game.gateway.ts
> +    });
game room id도 같이 찾아야되요!

2022-07-16 06:26 UTC, hsw7703 commented on backend/src/game/game.gateway.ts
> +    });
없어도 되요

2022-07-16 06:26 UTC, hsw7703 commented on backend/src/game/game.gateway.ts
> +    } else if (!existSpectator) {
left user, right user 둘다 있으면 무조건 spectator니까 else if -> else 쓰시면 될 거 같아요

2022-07-16 06:35 UTC, yeslee-v commented on backend/src/game/game.gateway.ts
> +    });
default positoin으로 spectator 설정했습니다

2022-07-16 06:43 UTC, hsw7703 approved these changes
드디어!!! 4번만에? 5번만에? 통과 했네요!!

2022-07-16 06:43 UTC, merged

2022-07-16 06:51 UTC, yeslee-v commented
db 연결 안됐던 것도 해결되서 너무 좋네요ㅠㅠ